# Generated by Django 5.0 on 2024-04-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("projectName", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=955)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", upload_to="projects/Images"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tileproducts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tileName", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=955)),
                ("cost", models.FloatField()),
                ("typeoftile", models.CharField(max_length=255)),
                ("lenghtoftile", models.CharField(max_length=20)),
                (
                    "image",
                    models.ImageField(default="", upload_to="tile_products/Images"),
                ),
            ],
        ),
    ]
