# Generated by Django 5.0 on 2024-06-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileproducts",
            name="id",
            field=models.AutoField(
                default=None, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
